[versions]
agp = "8.8.1"
androidmisc = "v0.0.5"

[libraries]
androidmisc = { module = "com.github.vova7878:AndroidMisc", version.ref = "androidmisc" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
maven-publish = { id = 'maven-publish' }

