[versions]
agp = "8.12.1"
raung = "v0.0.1"

[libraries]

[plugins]
raung = { id = "com.github.vova7878.RaungPlugin", version.ref = "raung" }
android-library = { id = "com.android.library", version.ref = "agp" }
maven-publish = { id = 'maven-publish' }
